#!/usr/bin/env python3
"""Generate docs/data.js from repo evidence files."""
import json, re, sys

def main():
    vflows_path  = sys.argv[1]
    ping_path    = sys.argv[2]
    before_path  = sys.argv[3] if len(sys.argv) > 3 else None
    after_path   = sys.argv[4] if len(sys.argv) > 4 else None

    evidence = json.load(open(vflows_path))
    ping     = open(ping_path).read()
    before   = open(before_path).read() if before_path else ""
    after    = open(after_path).read()  if after_path  else ""

    ping_blocks = ping.count("0% packet loss")

    topology = {
        "bridge": {"id": "br1", "label": "br1", "vlan": 100},
        "nodes": [
            {"id": "vm-a",         "type": "vm",  "ip": "10.10.0.10", "mac": "02:a0:00:00:00:0a"},
            {"id": "vm-b",         "type": "vm",  "ip": "10.10.0.11", "mac": "02:a0:00:00:00:0b"},
            {"id": "ovs-ping-pod", "type": "pod", "ip": "10.10.0.20", "mac": "02:a0:00:00:00:14"}
        ],
        "edges": [
            {"from": "vm-a",         "to": "br1"},
            {"from": "vm-b",         "to": "br1"},
            {"from": "ovs-ping-pod", "to": "br1"}
        ]
    }

    journey = [
        {
            "id": "bootstrap",
            "title": "Full stack bootstrap",
            "detail": "Single script provisions KinD, Open vSwitch, Multus, OVS-CNI, and KubeVirt end to end.",
            "proof": "cluster_setup.sh"
        },
        {
            "id": "kindnet",
            "title": "Flannel to kindnet",
            "problem": "Flannel crashed on recent kernels; subnet.env was never written; every pod sandbox failed.",
            "fix": "Switched to KinD built-in kindnet as the default CNI. OVS bridge layered on top via Multus.",
            "proof": "cluster_setup.sh (create_cluster)"
        },
        {
            "id": "vlan100",
            "title": "VLAN 100 access ports",
            "detail": "NAD declares vlan: 100. OVS attaches each veth as an access port that tags on ingress and strips on egress. push_vlan(vid=100) appears in datapath actions.",
            "proof": "manifests.yaml, verification_flows.json datapath_flows"
        },
        {
            "id": "classifiers",
            "title": "Per-source classifier rules",
            "detail": "install_classifier_flows() adds nw_src= rules before pings. flows_before.txt shows only the NORMAL catch-all; flows_after.txt shows all five rules with nonzero n_packets after the ping suite.",
            "proof": "evidence/flows_before.txt vs flows_after.txt"
        },
        {
            "id": "vmvm",
            "title": "VM-to-VM console pings",
            "detail": "virtctl console + expect drives bidirectional ping inside the CirrOS guests. Both directions captured with 0 percent packet loss.",
            "proof": "ping_results.txt directions 3 and 4"
        },
        {
            "id": "megaflows",
            "title": "Kernel megaflow cache captured",
            "detail": "ovs-appctl dpctl/dump-flows shows 20 per-MAC-pair entries installed by the pings. These are the exact objects that get offloaded to a BlueField-3 eSwitch via OVS-DOCA.",
            "proof": "verification_flows.json datapath_flows"
        },
        {
            "id": "ci",
            "title": "CI-gated reproducibility",
            "detail": "GitHub Actions run asserts 4 ping blocks, classifier rule hits with n_packets > 0, and a parser round-trip that confirms raw text and JSON match.",
            "proof": ".github/workflows/capture.yml, run 13"
        }
    ]

    data = {
        "meta":           evidence["_meta"],
        "bridge":         evidence["bridge"],
        "flows":          evidence["flows"],
        "datapathFlows":  evidence["datapath_flows"],
        "fdb":            evidence["fdb"],
        "ports":          evidence["ports"],
        "bridgeTopology": evidence.get("bridge_topology", ""),
        "pingBlocks":     ping_blocks,
        "pingText":       ping,
        "flowsBefore":    before,
        "flowsAfter":     after,
        "topology":       topology,
        "journey":        journey
    }

    print("/* AUTO-GENERATED by lab-console/gen_data.py — do not edit by hand */")
    print("window.APP_DATA = " + json.dumps(data, indent=2) + ";")

if __name__ == "__main__":
    main()
